name: Docker Status

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/**'
      - 'styles/*'
      - 'components/**'
      - 'postcss.config.js'
      - 'next.config.js'
      - 'package.json'
      - 'postcss.config.js'
      - 'tailwind.config.js'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'app/**'
      - 'styles/*'
      - 'components/**'
      - 'postcss.config.js'
      - 'next.config.js'
      - 'package.json'
      - 'postcss.config.js'
      - 'tailwind.config.js'
  workflow_dispatch:
permissions:
  id-token: write

jobs:
  build:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
     
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.API_TOKEN_GITHUB }}
        
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            blurred123131/speedjs:latest
            ghcr.io/${{ github.repository_owner }}/speedjs:latest

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1
        with:
          host: '68.218.3.24'
          username: 'azureuser'
          key: ${{ secrets.AZURE_KEY }}
          script: |
            sudo docker pull blurred123131/speedjs:latest
            sudo docker compose up -d
